name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25
          cache: gradle

      - name: Execution permission
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew assembleDebug

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: gyro-cursor-debug
          path: app/build/outputs/apk/debug/app-debug.apk
